# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cba7ce90b94857afd029308f7de4a13c"
name = "ShopOps"
application_url = "https://shopify-ops.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "ilafiu-dev.myshopify.com"

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory,read_inventory,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://shopify-ops.vercel.app/auth/callback" ]
