let
    // 1. DEFINICIÓN DE METADATOS PARA EL PANEL
    fnType = type function (
        GroupByField as (type text meta [
            Documentation.FieldCaption = "Nivel de Agrupación",
            Documentation.AllowedValues = {"day", "week", "month"},
            Documentation.LongDescription = "Selecciona la granularidad. 'week' activa la consolidación local para respetar el día ancla (ej. Viernes)."
        ]),
        FechaInicio as (type datetime meta [Documentation.FieldCaption = "Fecha Inicial"]),
        FechaFin as (type datetime meta [Documentation.FieldCaption = "Fecha Final"]),
        FechaRefresco as (type datetime meta [Documentation.FieldCaption = "Fecha Refrescar Histórico"]),
        optional NombreTablaHistorica as (type text meta [Documentation.FieldCaption = "Nombre Tabla Excel (Opcional)"])
    ) as table meta [
        Documentation.Name = "fnGetSessionsByReferrer",
        Documentation.LongDescription = "Obtiene sesiones, checkouts y tasa de conversión por fuente de referencia. #(cr,lf)Para 'week', consulta por día y agrupa localmente según el calendario personalizado.",
        Documentation.Examples = {[
            Description = "Obtener sesiones semanales",
            Code = "fnGetSessionsByReferrer(""week"", #datetime(2026,1,1,0,0,0), #datetime(2026,3,1,0,0,0), #datetime(2026,2,25,0,0,0))",
            Result = "Tabla combinada con detalle por fuente y totales del sitio por semana."
        ]}
    ],

    // 2. LÓGICA INTERNA
    FuncLogic = (
        GroupByField as text, 
        FechaInicio as datetime, 
        FechaFin as datetime, 
        FechaRefresco as datetime, 
        optional NombreTablaHistorica as text
    ) as table =>
    let
        SourceTable = "sessions",
        ColumnsToShow = "sessions, sessions_that_completed_checkout, conversion_rate",
        
        // RESTRICCIÓN TÉCNICA: Si es week, pedimos 'day' para agrupar nosotros
        ApiGroup = if GroupByField = "week" then "day" else GroupByField,

        // Obtención de periodos (Usando tu función ya restringida a 12 semanas)
        RawPeriods = fnGetDatesInPeriod(FechaInicio, FechaFin, FechaRefresco, GroupByField, ParamDiaSemanaReporte, NombreTablaHistorica),
        Periods = if RawPeriods is null or Table.IsEmpty(RawPeriods) then #table({"startDate", "endDate"}, {}) else RawPeriods,

        // --- FUNCIÓN INTERNA PARA PROCESAR LLAMADAS ---
        GetShopifyData = (IsTotal as logical) => 
            let
                CurrentGroupBy = if IsTotal then ApiGroup else ApiGroup & ", referrer_source",
                Prep = Table.AddColumn(Periods, "Query", each 
                    "FROM " & SourceTable & " SHOW " & ColumnsToShow & 
                    " GROUP BY " & CurrentGroupBy & 
                    " SINCE " & Date.ToText([startDate], "yyyy-MM-dd") & 
                    " UNTIL " & Date.ToText([endDate], "yyyy-MM-dd")
                ),
                Invoke = Table.AddColumn(Prep, "Data", each try fnGetShopifyQLData([Query]) otherwise null),
                Valid = Table.SelectRows(Invoke, each [Data] <> null and not ([Data] is text and [Data] = "")),
                
                Expand = if Table.IsEmpty(Valid) then #table({},{}) else
                    let
                        ExpList = Table.ExpandListColumn(Valid, "Data"),
                        Cols = if IsTotal then {ApiGroup, "sessions", "sessions_that_completed_checkout"} 
                               else {ApiGroup, "referrer_source", "sessions", "sessions_that_completed_checkout"},
                        ExpRec = Table.ExpandRecordColumn(ExpList, "Data", Cols),
                        // Tipado numérico para poder sumar
                        ToNum = Table.TransformColumnTypes(ExpRec, {{"sessions", Int64.Type}, {"sessions_that_completed_checkout", Int64.Type}}),
                        
                        // --- CONSOLIDACIÓN LOCAL SI ES SEMANA ---
                        Consolidate = if GroupByField = "week" then
                            Table.Group(ToNum, if IsTotal then {"startDate"} else {"startDate", "referrer_source"}, {
                                {"sessions", each List.Sum([sessions]), Int64.Type},
                                {"sessions_that_completed_checkout", each List.Sum([sessions_that_completed_checkout]), Int64.Type}
                            })
                            else Table.RemoveColumns(ToNum, {"endDate", "Query"})
                    in
                        Consolidate
            in
                Expand,

        // Ejecutar ambas ramas
        TableDetail = GetShopifyData(false),
        TableTotal = GetShopifyData(true),
        
        // Formatear Total site
        FormatTotal = if Table.IsEmpty(TableTotal) then TableTotal else Table.AddColumn(TableTotal, "referrer_source", each "Total site"),

        // 4. COMBINAR Y NORMALIZAR
        CombinedTable = Table.Combine({TableDetail, FormatTotal}),
        
        FinalResults = if Table.IsEmpty(CombinedTable) then 
            #table({GroupByField, "referrer_source", "sessions", "sessions_that_completed_checkout", "conversion_rate", "refresh_date"}, {})
        else
            let
                // Si consolidamos por semana, la columna se llama startDate, la renombramos al GroupByField
                RenameAxis = if GroupByField = "week" then Table.RenameColumns(CombinedTable, {{"startDate", "week"}}) else CombinedTable,
                
                TransformDate = Table.TransformColumns(RenameAxis, {
                    {GroupByField, each try if GroupByField = "month" and Text.Length(Text.From(_)) <= 7 then Text.From(_) & "-01" else _ otherwise _, type text}
                }),
                
                Typed = Table.TransformColumnTypes(TransformDate, {
                    {GroupByField, type date},
                    {"referrer_source", type text},
                    {"sessions", Int64.Type},
                    {"sessions_that_completed_checkout", Int64.Type}
                }),
                
                // Recalcular Tasa de Conversión (La suma de tasas de Shopify no sirve, hay que recalcular sobre totales)
                AddCR = Table.AddColumn(Typed, "conversion_rate", each if [sessions] > 0 then [sessions_that_completed_checkout] / [sessions] else 0, type number),
                
                AddedRefresh = Table.AddColumn(AddCR, "refresh_date", each DateTime.LocalNow(), type datetime)
            in
                Table.SelectColumns(AddedRefresh, {GroupByField, "referrer_source", "sessions", "sessions_that_completed_checkout", "conversion_rate", "refresh_date"})
    in
        FinalResults
in
    Value.ReplaceType(FuncLogic, fnType)
