let
    // 1. DEFINICIÓN DE METADATOS (Para el panel de la función)
    fnType = type function (
        GroupByField as (type text meta [
            Documentation.FieldCaption = "Nivel de Agrupación",
            Documentation.AllowedValues = {"day", "week", "month"},
            Documentation.LongDescription = "Selecciona el nivel de detalle temporal. Nota: 'week' usa agrupación local para mayor precisión."
        ]),
        FechaInicio as (type datetime meta [
            Documentation.FieldCaption = "Fecha Inicial",
            Documentation.SampleValues = {"2026-01-01T00:00:00"}
        ]),
        FechaFin as (type datetime meta [
            Documentation.FieldCaption = "Fecha Final",
            Documentation.SampleValues = {"2026-12-31T23:59:59"}
        ]),
        FechaRefresco as (type datetime meta [
            Documentation.FieldCaption = "Fecha Refrescar Histórico",
            Documentation.LongDescription = "Cualquier registro igual o posterior a esta fecha será regenerado desde la API."
        ]),
        optional NombreTablaHistorica as (type text meta [
            Documentation.FieldCaption = "Nombre Tabla Excel (Opcional)",
            Documentation.LongDescription = "Nombre de la tabla donde se guardan los datos históricos para habilitar carga incremental."
        ])
    ) as table meta [
        Documentation.Name = "fnGetSalesBreakdownByPeriod",
        Documentation.LongDescription = "Consulta métricas de ventas de ShopifyQL con optimización de periodos. Resuelve el desfase de semanas de Shopify mediante agrupación local por día.",
        Documentation.Examples = {
            [
                Description = "Consulta de ventas semanales",
                Code = "fnGetSalesBreakdownByPeriod(""week"", #datetime(2026,1,1,0,0,0), #datetime(2026,2,1,0,0,0), #datetime(2026,1,20,0,0,0))",
                Result = "Tabla con métricas de ventas agrupadas por tu semana personalizada."
            ]
        }
    ],

    // 2. LÓGICA INTERNA DE LA FUNCIÓN
    FuncLogic = (
        GroupByField as text, 
        FechaInicio as datetime, 
        FechaFin as datetime, 
        FechaRefresco as datetime, 
        optional NombreTablaHistorica as text
    ) as table =>
    let
        SourceTable = "sales",
        ColumnsToShow = "orders, quantity_ordered_per_order, average_order_value, quantity_returned, gross_sales, discounts, sales_reversals, net_sales, shipping_charges, return_fees, taxes, total_sales, net_sales_without_cost_recorded, net_sales_with_cost_recorded, cost_of_goods_sold, gross_profit, gift_card_gross_sales, net_items_sold, gift_card_discounts, gift_card_net_sales",

        // Obtención de periodos usando la lógica optimizada
        Periods = fnGetDatesInPeriod(FechaInicio, FechaFin, FechaRefresco, GroupByField, ParamDiaSemanaReporte, NombreTablaHistorica),

        // Construcción de la consulta: Si es week, pedimos day para agrupar localmente
        PreparedQueries = Table.AddColumn(Periods, "CustomQuery", each 
            "FROM " & SourceTable & " " & 
            "SHOW " & ColumnsToShow & " " & 
            "GROUP BY " & (if GroupByField = "week" then "day" else GroupByField) & " " & 
            "SINCE " & Date.ToText([startDate], "yyyy-MM-dd") & " " & 
            "UNTIL " & Date.ToText([endDate], "yyyy-MM-dd")
        , type text),

        InvokeAPI = Table.AddColumn(PreparedQueries, "Data", each fnGetShopifyQLData([CustomQuery])),
        ValidData = Table.SelectRows(InvokeAPI, each [Data] <> null and [Data] <> ""),

        ResultTable = if Table.IsEmpty(ValidData) then 
            #table(Text.Split(GroupByField & "," & ColumnsToShow, ","), {})
        else
            let
                ExpandedList = Table.ExpandListColumn(ValidData, "Data"),
                ApiColumnName = if GroupByField = "week" then "day" else GroupByField,
                ColumnNames = List.Transform(Text.Split(ApiColumnName & "," & ColumnsToShow, ","), Text.Trim),
                ExpandedRecords = Table.ExpandRecordColumn(ExpandedList, "Data", ColumnNames),

                MetricsList = List.Transform(Text.Split(ColumnsToShow, ","), Text.Trim),
                TypedForAggregation = Table.TransformColumnTypes(ExpandedRecords, 
                    List.Transform(MetricsList, each {_, type number})),

                // Consolidación para evitar desalineación de Shopify
                FinalData = if GroupByField = "week" then
                    let
                        GroupedByCustomWeek = Table.Group(TypedForAggregation, {"startDate", "endDate"}, 
                            List.Transform(MetricsList, (col) => {col, each List.Sum(Table.Column(_, col)), type number})
                        ),
                        AddWeekCol = Table.AddColumn(GroupedByCustomWeek, "week", each [startDate], type date)
                    in
                        AddWeekCol
                else
                    let
                        TransformPeriod = Table.TransformColumns(TypedForAggregation, {
                            {GroupByField, each if GroupByField = "month" and Text.Length(Text.From(_)) <= 7 then Text.From(_) & "-01" else Text.From(_), type text}
                        }),
                        TypedDate = Table.TransformColumnTypes(TransformPeriod, {{GroupByField, type date}})
                    in
                        TypedDate
            in
                FinalData,

        ActualColumns = Table.ColumnNames(ResultTable),
        ColumnsToRemove = List.Intersect({ActualColumns, {"CustomQuery", "startDate", "endDate"}}),
        RemovedColumns = Table.RemoveColumns(ResultTable, ColumnsToRemove),
        
        SortedRows = Table.Sort(RemovedColumns, {{GroupByField, Order.Ascending}}),
        UpdateColumn = Table.AddColumn(SortedRows, "refresh_date", each DateTime.LocalNow(), type datetime)
    in
        UpdateColumn
in
    Value.ReplaceType(FuncLogic, fnType)
