let
    // 1. DEFINICIÓN DE METADATOS
    fnType = type function (
        GroupByField as (type text meta [
            Documentation.FieldCaption = "Nivel de Agrupación",
            Documentation.AllowedValues = {"day", "week", "month"}
        ]),
        FechaInicio as (type datetime),
        FechaFin as (type datetime),
        FechaRefresco as (type datetime),
        optional NombreTablaHistorica as (type text)
    ) as table meta [
        Documentation.Name = "fnSalesNewReturning",
        Documentation.LongDescription = "Versión Ultra-Blindada. Corrige error de nulos en Header y colisiones de nombres month/day."
    ],

    FuncLogic = (
        GroupByField as text, 
        FechaInicio as datetime, 
        FechaFin as datetime, 
        FechaRefresco as datetime, 
        optional NombreTablaHistorica as text
    ) as table =>
    let
        SourceTable = "sales",
        ColumnsToShow = "customers, orders, net_sales, average_order_value, cost_of_goods_sold, gross_profit",
        
        ApiTimeGroup = if GroupByField = "week" then "day" else GroupByField,
        ShopifyGroup = "new_or_returning_customer, " & ApiTimeGroup,

        Periods = fnGetDatesInPeriod(FechaInicio, FechaFin, FechaRefresco, GroupByField, ParamDiaSemanaReporte, NombreTablaHistorica),

        // 1. PRE-LIMPIEZA: Evitar colisiones con day/month/startDate/endDate
        RenamedPeriods = Table.RenameColumns(Periods, {{"startDate", "base_startDate"}, {"endDate", "base_endDate"}}),

        PreparedQueries = Table.AddColumn(RenamedPeriods, "CustomQuery", each 
            "FROM " & SourceTable & " " & 
            "SHOW " & ColumnsToShow & " " & 
            "GROUP BY " & ShopifyGroup & " " & 
            "SINCE " & Date.ToText([base_startDate], "yyyy-MM-dd") & " " & 
            "UNTIL " & Date.ToText([base_endDate], "yyyy-MM-dd")
        , type text),

        InvokeAPI = Table.AddColumn(PreparedQueries, "Data", each try fnGetShopifyQLData([CustomQuery]) otherwise null),
        ValidData = Table.SelectRows(InvokeAPI, each [Data] <> null and [Data] <> ""),

        ResultTable = if Table.IsEmpty(ValidData) then 
            #table({if GroupByField = "week" then "week" else GroupByField}, {}) 
        else
            let
                // 2. EXPANSIÓN CON PREFIJO (Evita colisión con 'month' y 'day')
                ExpandedList = Table.ExpandListColumn(ValidData, "Data"),
                SampleRecord = List.First(ExpandedList[Data]),
                FieldsInRecord = Record.FieldNames(SampleRecord),
                ExpandedResults = Table.ExpandRecordColumn(ExpandedList, "Data", FieldsInRecord, List.Transform(FieldsInRecord, each "api_" & _)),

                MetricList = List.Transform(Text.Split(ColumnsToShow, ","), Text.Trim),

                // 3. TRATAMIENTO CRÍTICO DE NULOS (Evita el error de conversión a Text)
                // Reemplazamos nulos en la dimensión del cliente antes de cualquier operación de texto
                FixedNulls = Table.ReplaceValue(ExpandedResults, null, "unknown", Replacer.ReplaceValue, {"api_new_or_returning_customer"}),

                // 4. NORMALIZACIÓN DE EJES
                TimeNormalized = if GroupByField = "week" then 
                                    Table.DuplicateColumn(FixedNulls, "base_startDate", "week") 
                                 else 
                                    Table.RenameColumns(FixedNulls, {{"base_startDate", GroupByField}}),

                // 5. CONSOLIDACIÓN
                Consolidated = if GroupByField = "week" then
                    Table.Group(TimeNormalized, {"week", "base_endDate", "api_new_or_returning_customer"}, 
                        List.Transform(MetricList, (col) => {col, each List.Sum(Table.Column(Table.TransformColumnTypes(_, {{"api_" & col, type number}}), "api_" & col)), type number})
                    )
                else 
                    Table.RenameColumns(TimeNormalized, List.Transform(MetricList, each {"api_" & _, _})),

                // 6. PIVOTE Y LIMPIEZA DE SOBRANTES (api_day, api_month, etc.)
                RequiredDims = if GroupByField = "week" then {"week", "base_endDate", "api_new_or_returning_customer"} else {GroupByField, "api_new_or_returning_customer"},
                
                // SelectColumns elimina las columnas colisionadas de la API (api_day, api_month)
                CleanTable = Table.SelectColumns(Consolidated, List.Combine({RequiredDims, MetricList})),

                Unpivoted = Table.UnpivotOtherColumns(CleanTable, RequiredDims, "Metric", "Value"),
                
                // Header seguro contra nulos
                MergedHeader = Table.AddColumn(Unpivoted, "Header", each 
                    let 
                        CustomerType = if [api_new_or_returning_customer] = null then "unknown" else Text.Lower(Text.Replace(Text.From([api_new_or_returning_customer]), " ", "_"))
                    in 
                        CustomerType & "_" & Text.Replace([Metric], "api_", ""), type text),
                
                FinalTimeCols = if GroupByField = "week" then {"week", "base_endDate"} else {GroupByField},
                PivotPrep = Table.SelectColumns(MergedHeader, List.Combine({FinalTimeCols, {"Header", "Value"}})),
                
                Pivoted = Table.Pivot(PivotPrep, List.Distinct(PivotPrep[Header]), "Header", "Value", List.Sum),
                
                FinalResult = if GroupByField = "week" then Table.RenameColumns(Pivoted, {{"base_endDate", "endDate"}}) else Pivoted
            in
                FinalResult,

        // 7. TIPADO Y ORDEN
        AllCols = Table.ColumnNames(ResultTable),
        TypedTable = List.Accumulate(AllCols, ResultTable, (state, current) =>
            if List.Contains({GroupByField, "week", "endDate"}, current) then Table.TransformColumnTypes(state, {{current, type date}})
            else if Text.Contains(current, "orders") or Text.Contains(current, "customers") then Table.TransformColumnTypes(state, {{current, Int64.Type}})
            else Table.TransformColumnTypes(state, {{current, type number}})
        ),

        SortCol = if GroupByField = "week" then "week" else GroupByField,
        Sorted = Table.Sort(TypedTable, {{SortCol, Order.Ascending}}),
        Output = Table.AddColumn(Sorted, "refresh_date", each DateTime.LocalNow(), type datetime)
    in
        Output
in
    Value.ReplaceType(FuncLogic, fnType)
