let
    // 1. DEFINICIÓN DE LA LÓGICA INTERNA
    FuncLogic = (
        GroupByField as text, 
        FechaInicio as datetime, 
        FechaFin as datetime, 
        FechaRefresco as datetime, 
        optional NombreTablaHistorica as text
    ) as table =>
    let
        SourceTable = "sales",
        ColumnsToShow = "quantity_ordered, net_sales",
        MetafieldColumn = "order.metafields.custom.origen_venta",
        
        // RESTRICCIÓN: Si es week, pedimos 'day' para agrupar localmente según el ancla personalizada
        ApiTimeGroup = if GroupByField = "week" then "day" else GroupByField,
        FullGroupBy = ApiTimeGroup & ", " & MetafieldColumn & ", product_title, new_or_returning_customer",

        // 2. GENERACIÓN DE PERIODOS
        Periods = fnGetDatesInPeriod(FechaInicio, FechaFin, FechaRefresco, GroupByField, ParamDiaSemanaReporte, NombreTablaHistorica),

        // 3. CONSTRUCCIÓN DE CONSULTAS
        PreparedQueries = Table.AddColumn(Periods, "CustomQuery", each 
            "FROM " & SourceTable & " " &
            "SHOW " & ColumnsToShow & " " &
            "GROUP BY " & FullGroupBy & " " &
            "SINCE " & Date.ToText([startDate], "yyyy-MM-dd") & " " & 
            "UNTIL " & Date.ToText([endDate], "yyyy-MM-dd") & " " &
            "ORDER BY quantity_ordered DESC"
        , type text),

        // 4. INVOCACIÓN API
        InvokeAPI = Table.AddColumn(PreparedQueries, "Data", each fnGetShopifyQLData([CustomQuery])),
        ValidData = Table.SelectRows(InvokeAPI, each [Data] <> null and [Data] <> ""),

        ResultTable = if Table.IsEmpty(ValidData) then 
            #table({GroupByField, "source", "product_title", "new_or_returning_customer", "quantity_ordered", "net_sales"}, {})
        else
            let
                // 5. EXPANSIÓN Y LIMPIEZA INICIAL
                ExpandedList = Table.ExpandListColumn(ValidData, "Data"),
                ColumnsToExpand = {MetafieldColumn, "product_title", "quantity_ordered", "new_or_returning_customer", "net_sales", ApiTimeGroup},
                ExpandedRecords = Table.ExpandRecordColumn(ExpandedList, "Data", ColumnsToExpand),
                
                // Normalización de tipos para consolidación
                PreTyped = Table.TransformColumnTypes(ExpandedRecords, {
                    {"quantity_ordered", Int64.Type},
                    {"net_sales", type number}
                }),

                // 6. CONSOLIDACIÓN LOCAL PARA 'WEEK'
                Consolidated = if GroupByField = "week" then
                    Table.Group(PreTyped, {"startDate", MetafieldColumn, "product_title", "new_or_returning_customer"}, {
                        {"quantity_ordered", each List.Sum([quantity_ordered]), Int64.Type},
                        {"net_sales", each List.Sum([net_sales]), type number}
                    })
                    else PreTyped,

                // 7. LIMPIEZA DE DIMENSIONES
                CleanMetafields = Table.TransformColumns(Consolidated, {
                    {MetafieldColumn, each if _ is list then Text.Combine(List.Transform(_, each Text.From(_)), ", ") else Text.From(_)}
                }),

                Renamed = Table.RenameColumns(CleanMetafields, {
                    {MetafieldColumn, "source"},
                    {if GroupByField = "week" then "startDate" else GroupByField, GroupByField}
                }),

                // 8. TRATAMIENTO DE FECHA (Meses)
                TransformDate = Table.TransformColumns(Renamed, {
                    {GroupByField, each 
                        if GroupByField = "month" and Text.Length(Text.From(_)) <= 7 
                        then Text.From(_) & "-01" 
                        else _, 
                    type text}
                }),

                // --- 9. LIMPIEZA DE COLUMNAS SOBRANTES (PRODUCCIÓN) ---
                FinalColumns = Table.SelectColumns(TransformDate, {
                    GroupByField, 
                    "source", 
                    "product_title", 
                    "new_or_returning_customer", 
                    "quantity_ordered", 
                    "net_sales"
                })
            in
                FinalColumns,

        // 10. ASIGNACIÓN DE TIPOS FINALES
        AllColumns = Table.ColumnNames(ResultTable),
        TypedTable = List.Accumulate(AllColumns, ResultTable, (state, current) =>
            if current = GroupByField then Table.TransformColumnTypes(state, {{current, type date}})
            else if current = "quantity_ordered" then Table.TransformColumnTypes(state, {{current, Int64.Type}})
            else if current = "net_sales" then Table.TransformColumnTypes(state, {{current, type number}})
            else Table.TransformColumnTypes(state, {{current, type text}})
        ),

        AddedRefreshDate = Table.AddColumn(TypedTable, "refresh_date", each DateTime.LocalNow(), type datetime),
        CleanSource = Table.ReplaceValue(AddedRefreshDate, "", "Online store", Replacer.ReplaceValue, {"source"}),
        Final = Table.Sort(CleanSource, {{GroupByField, Order.Ascending}, {"source", Order.Ascending}, {"net_sales", Order.Descending}})
    in
        Final,

    // DOCUMENTACIÓN
    TypeFunction = type function (
        GroupByField as (type text meta [
            Documentation.FieldCaption = "Nivel de Agrupación",
            Documentation.AllowedValues = {"day", "week", "month"}
        ]),
        FechaInicio as (type datetime),
        FechaFin as (type datetime),
        FechaRefresco as (type datetime),
        optional NombreTablaHistorica as (type text)
    ) as table meta [
        Documentation.Name = "fnGetSalesDetailedByPeriod",
        Documentation.LongDescription = "Consulta detallada de ventas (producto, origen, cliente) con limpieza automática de columnas técnicas."
    ]
in
    Value.ReplaceType(FuncLogic, TypeFunction)
