let
    FuncLogic = (
        FechaInicioReporte as datetime, 
        FechaFinReporte as datetime, 
        FechaRefrescoReporte as datetime, 
        Tipo as text, 
        ParamDiaSemanaReporte as number,
        optional NombreTablaHistorica as text
    ) as table =>
    let
        // --- CONFIGURACIÓN DE RESTRICCIONES (Hardcoded como solicitaste) ---
        LimiteDiasAtras = 365,      // 1 año para tipo "day"
        LimiteSemanasMax = 12,     // Máximo 12 semanas (aprox 3 meses) para tipo "week"

        // Conversión de tipos datetime a date
        Hoy = DateTime.Date(DateTime.LocalNow()),
        FechaFinRef = Date.From(FechaFinReporte),
        FechaRefresco = Date.From(FechaRefrescoReporte),

        // --- APLICACIÓN DE RESTRICCIONES ---
        FechaInicioRaw = Date.From(FechaInicioReporte),
        
        FechaInicio = if Tipo = "day" then 
                List.Max({FechaInicioRaw, Date.AddDays(Hoy, -LimiteDiasAtras)}) 
            else if Tipo = "week" then 
                List.Max({FechaInicioRaw, Date.AddDays(FechaFinRef, -(LimiteSemanasMax * 7))})
            else FechaInicioRaw,

        FechaFin = FechaFinRef,

        // 1. GENERACIÓN DE LA LISTA BASE SEGÚN EL TIPO
        ListaPeriodos = if Tipo = "day" then 
                List.Dates(FechaInicio, Duration.Days(FechaFin - FechaInicio) + 1, #duration(1, 0, 0, 0))
            else if Tipo = "week" then
                let
                    DiaActual = Date.DayOfWeek(FechaInicio, Day.Sunday),
                    Diferencia = Number.Mod(DiaActual - ParamDiaSemanaReporte + 7, 7),
                    PrimerDiaSemana = Date.AddDays(FechaInicio, -Diferencia)
                in
                    List.Generate(() => PrimerDiaSemana, each _ <= FechaFin, each Date.AddDays(_, 7))
            else 
                let
                    Cant = ((Date.Year(FechaFin) - Date.Year(FechaInicio)) * 12) + (Date.Month(FechaFin) - Date.Month(FechaInicio)),
                    Meses = List.Transform({0..Cant}, each Date.StartOfMonth(Date.AddMonths(FechaInicio, _)))
                in Meses,

        // 2. TABLA BASE E ÍNDICE DE CONTINUIDAD
        TablaBase = Table.FromList(ListaPeriodos, Splitter.SplitByNothing(), {Tipo}),
        TypedBase = Table.TransformColumnTypes(TablaBase, {{Tipo, type date}}),
        AddOriginalIndex = Table.AddIndexColumn(TypedBase, "OriginalIndex", 0, 1),

        // 3. FILTRADO CON VALIDACIÓN DE REFRESH (Lógica Incremental)
        Filtrado = if NombreTablaHistorica = null or NombreTablaHistorica = "" then AddOriginalIndex
            else
                let
                    Acceso = try Excel.CurrentWorkbook(){[Name=NombreTablaHistorica]}[Content] otherwise null,
                    ColOk = if Acceso <> null then Table.HasColumns(Acceso, {Tipo}) else false,
                    Result = if ColOk then
                        let
                            Existentes = List.Buffer(Table.Column(Table.TransformColumnTypes(Acceso, {{Tipo, type date}}), Tipo)),
                            Filtro = Table.SelectRows(AddOriginalIndex, each 
                                not List.Contains(Existentes, Record.Field(_, Tipo)) or 
                                Record.Field(_, Tipo) >= FechaRefresco
                            )
                        in Filtro
                    else AddOriginalIndex
                in Result,

        // 4. LÓGICA CONDICIONAL DE SALIDA
        Sorted = Table.Sort(Filtrado, {{Tipo, Order.Ascending}}),
        
        ResultadoFinal = if Tipo = "week" then
            let
                Individual = Table.AddColumn(Sorted, "startDate", each Record.Field(_, Tipo), type date),
                EndDates = Table.AddColumn(Individual, "endDate", each Date.AddDays([startDate], 6), type date)
            in
                Table.SelectColumns(EndDates, {"startDate", "endDate"})
        else
            let
                AddGroupIndex = Table.AddIndexColumn(Sorted, "GroupIndex", 0, 1),
                GroupId = Table.AddColumn(AddGroupIndex, "GroupId", each [OriginalIndex] - [GroupIndex]),
                Aggregated = Table.Group(GroupId, {"GroupId"}, {
                    {"startDate", each List.Min(Table.Column(_, Tipo)), type date},
                    {"endDate", each 
                        if Tipo = "day" then List.Max(Table.Column(_, Tipo)) 
                        else Date.EndOfMonth(List.Max(Table.Column(_, Tipo))), type date}
                })
            in
                Table.RemoveColumns(Aggregated, {"GroupId"})
    in
        ResultadoFinal,

    // DOCUMENTACIÓN ACTUALIZADA CON RESTRICCIONES
    fnType = type function (
        FechaInicioReporte as (type datetime meta [
            Documentation.FieldCaption = "Fecha Inicio Reporte",
            Documentation.SampleValues = {"2025-01-01T00:00:00"}
        ]),
        FechaFinReporte as (type datetime meta [Documentation.FieldCaption = "Fecha Fin Reporte"]),
        FechaRefrescoReporte as (type datetime meta [Documentation.FieldCaption = "Fecha Refresco Histórico"]),
        Tipo as (type text meta [
            Documentation.FieldCaption = "Nivel de Agrupación",
            Documentation.AllowedValues = {"day", "week", "month"}
        ]),
        ParamDiaSemanaReporte as (type number meta [Documentation.FieldCaption = "Día Ancla (Excel)"]),
        optional NombreTablaHistorica as (type text meta [Documentation.FieldCaption = "Nombre Tabla Excel Histórica"])
    ) as table meta [
        Documentation.Name = "fnGetDatesInPeriod",
        Documentation.LongDescription = "Genera rangos de fechas optimizados para la API de Shopify. 
        #(cr,lf)RESTRICCIONES DE SEGURIDAD:
        #(cr,lf)- Para 'day': Máximo 365 días atrás desde hoy.
        #(cr,lf)- Para 'week': Máximo 12 semanas (3 meses) desde la Fecha Fin.
        #(cr,lf)Agrupa días y meses consecutivos para reducir llamadas, manteniendo semanas desglosadas individualmente.",
        Documentation.Examples = {
            [
                Description = "Generar semanas restringidas a máximo 12",
                Code = "fnGetDatesInPeriod(#datetime(2024,1,1,0,0,0), #datetime(2026,5,8,0,0,0), #datetime(2026,4,1,0,0,0), ""week"", 5)",
                Result = "Tabla con las últimas 12 semanas (por restricción) ancladas a Viernes."
            ]
        }
    ]
in
    Value.ReplaceType(FuncLogic, fnType)
