let
    // 1. Origen principal
    Origen = SalesBreakdownDaily,

    // 2. Unión con Ventas Nuevos vs Recurrentes
    JoinNuevosRecurrentes = Table.NestedJoin(Origen, {"day"}, SalesNewReturningDaily, {"day"}, "SalesNewReturning", JoinKind.LeftOuter),
    ExpandNuevosRecurrentes = Table.ExpandTableColumn(JoinNuevosRecurrentes, "SalesNewReturning", 
        {"returning_customers", "returning_orders", "returning_net_sales", "returning_average_order_value", "returning_cost_of_goods_sold", "returning_gross_profit", "new_customers", "new_orders", "new_net_sales", "new_average_order_value", "new_cost_of_goods_sold", "new_gross_profit", "unknown_customers", "unknown_orders", "unknown_net_sales", "unknown_average_order_value", "unknown_cost_of_goods_sold", "unknown_gross_profit"}, 
        {"returning_customers", "returning_orders", "returning_net_sales", "returning_average_order_value", "returning_cost_of_goods_sold", "returning_gross_profit", "new_customers", "new_orders", "new_net_sales", "new_average_order_value", "new_cost_of_goods_sold", "new_gross_profit", "unknown_customers", "unknown_orders", "unknown_net_sales", "unknown_average_order_value", "unknown_cost_of_goods_sold", "unknown_gross_profit"}),

    // 5. Unión con Ventas por Fuente (Canales)
    JoinSalesBySource = Table.NestedJoin(ExpandNuevosRecurrentes, {"day"}, SalesBySourceToColsDaily, {"day"}, "SalesBySourceToCols", JoinKind.LeftOuter),
    ExpandSalesBySource = Table.ExpandTableColumn(JoinSalesBySource, "SalesBySourceToCols", 
        {"Online Store_net_sales", "Online Store_orders", "Online Store_average_order_value", "Online Store_cost_of_goods_sold", "Tienda 81_net_sales", "Tienda 81_orders", "Tienda 81_average_order_value", "Tienda 81_cost_of_goods_sold", "Rappi_net_sales", "Rappi_orders", "Rappi_average_order_value", "Rappi_cost_of_goods_sold", "Corporativo no tienda_net_sales", "Corporativo no tienda_orders", "Corporativo no tienda_average_order_value", "Corporativo no tienda_cost_of_goods_sold"}, 
        {"Online Store_net_sales", "Online Store_orders", "Online Store_average_order_value", "Online Store_cost_of_goods_sold", "Tienda 81_net_sales", "Tienda 81_orders", "Tienda 81_average_order_value", "Tienda 81_cost_of_goods_sold", "Rappi_net_sales", "Rappi_orders", "Rappi_average_order_value", "Rappi_cost_of_goods_sold", "Corporativo no tienda_net_sales", "Corporativo no tienda_orders", "Corporativo no tienda_average_order_value", "Corporativo no tienda_cost_of_goods_sold"}),

    // 6. Unión con Tasa de Conversión por Referido
    JoinConversionRate = Table.NestedJoin(ExpandSalesBySource, {"day"}, ConversionRateToColsDaily, {"day"}, "ConversionRateByReferral", JoinKind.LeftOuter),
    ExpandConversionRate = Table.ExpandTableColumn(JoinConversionRate, "ConversionRateByReferral", 
        {"unknown_sessions", "unknown_sessions_that_completed_checkout", "unknown_conversion_rate", "social_sessions", "social_sessions_that_completed_checkout", "social_conversion_rate", "search_sessions", "search_sessions_that_completed_checkout", "search_conversion_rate", "paid_sessions", "paid_sessions_that_completed_checkout", "paid_conversion_rate", "direct_sessions", "direct_sessions_that_completed_checkout", "direct_conversion_rate", "Total site_sessions", "Total site_sessions_that_completed_checkout", "Total site_conversion_rate", "email_sessions", "email_sessions_that_completed_checkout", "email_conversion_rate"}, 
        {"unknown_sessions", "unknown_sessions_that_completed_checkout", "unknown_conversion_rate", "social_sessions", "social_sessions_that_completed_checkout", "social_conversion_rate", "search_sessions", "search_sessions_that_completed_checkout", "search_conversion_rate", "paid_sessions", "paid_sessions_that_completed_checkout", "paid_conversion_rate", "direct_sessions", "direct_sessions_that_completed_checkout", "direct_conversion_rate", "Total site_sessions", "Total site_sessions_that_completed_checkout", "Total site_conversion_rate", "email_sessions", "email_sessions_that_completed_checkout", "email_conversion_rate"}),
    // 3. Unión con Google Ads (Ajustado a columna 'day')
    JoinGoogleAds = Table.NestedJoin(ExpandConversionRate, {"day"}, GoogleAdsOperationDaily, {"day"}, "GoogleAdsOperation", JoinKind.LeftOuter),
    ExpandGoogleAds = Table.ExpandTableColumn(JoinGoogleAds, "GoogleAdsOperation", 
        {"Cost", "Avg. Cpc", "Ctr", "Search Impr. share", "Impressions", "Clicks"}, 
        {"GoogleAdsOperation.Cost", "GoogleAdsOperation.Avg. Cpc", "GoogleAdsOperation.Ctr", "GoogleAdsOperation.Search Impr. share", "GoogleAdsOperation.Impressions", "GoogleAdsOperation.Clicks"}),
    // 4. Unión con Meta Ads (Agregación de Spend, Clicks e Impressions)
    JoinMetaAds = Table.NestedJoin(ExpandGoogleAds, {"day"}, MetaAdsOperationDaily, {"day"}, "MetaAdsOperation", JoinKind.LeftOuter),
    AggregateMetaAds = Table.AggregateTableColumn(JoinMetaAds, "MetaAdsOperation", {
        {"spend", List.Sum, "MetaAdsOperation.spend"}, 
        {"clicks", List.Sum, "MetaAdsOperation.clicks"}, 
        {"impressions", List.Sum, "MetaAdsOperation.impressions"}
    }),
    ChangeTypes = Table.TransformColumnTypes(AggregateMetaAds,{{"MetaAdsOperation.spend", Int64.Type}, {"MetaAdsOperation.clicks", Int64.Type}, {"MetaAdsOperation.impressions", Int64.Type}})
in
    ChangeTypes
